### ISSUE TITLE
Add this to the Godot Asset Library

### ISSUE THREAD

**Issue by ZachAR3** [ZachAR3/GodotOpenInEditor#3]
Add this plugin to the Godot asset library for ease of use. @Creta5164 is it ok if I put this up there? It will be free and just link back to this, but wanted to double check. I asked in your original Github Gist but you must not have seen it.

**Comment by Creta5164** [comment]
@ZachAR3 Agreed, hopefully this can take major coverage around Godot users.

Consider add some unit test of various external text editor for QoL later, I'd like to put VSCode support again!

**Comment by ZachAR3** [comment]
> @ZachAR3 Agreed, hopefully this can take major coverage around Godot users.
> 
> Consider add some unit test of various external text editor for QoL later, I'd like to put VSCode support again!

VSCode is supported though? It works perfect on my system, does it create issues for you? I'm on Linux so maybe the windows pathing is a bit different which causes issues with it.

**Comment by Creta5164** [comment]
@ZachAR3 I think I talked little confusing, I mean hopefully supports basic integration features of each third party text editors, in example, my original addone does can open workspace instead when choose multiple directories to open.

![image-41.png](https://github.com/ZachAR3/GodotOpenInEditor/assets/13521406/2c0b3673-b94c-469f-b0f3-6a8e1e934c90)

This is just my opinion, but I think it should have able open multiple file feature at least.

**Comment by ZachAR3** [comment]
> @ZachAR3 I think I talked little confusing, I mean hopefully supports basic integration features of each third party text editors, in example, my original addone does can open workspace instead when choose multiple directories to open.
> 
> ![image-41.png](https://private-user-images.githubusercontent.com/13521406/330533159-2c0b3673-b94c-469f-b0f3-6a8e1e934c90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTIxMzYsIm5iZiI6MTcxNTg1MTgzNiwicGF0aCI6Ii8xMzUyMTQwNi8zMzA1MzMxNTktMmMwYjM2NzMtYjk0Yy00NjlmLWIwZjMtNmE4ZTFlOTM0YzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA5MzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliY2NmZTM4ZmZhNTc5ZmQ0ZjA5YjY1YjEyMTdhYjk2MzI4NzQ2OGM0MzE3MDI4OTExMDcxMDg2MzgyMjA5ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NO9CaZBgNT7AAtaa7uAlEYPLheW0aCc6kRBPdR988YE)
> 
> This is just my opinion, but I think it should have able open multiple file feature at least.

Im still a bit confused as to what you mean, but feel free to create an issue detailing the feature
