### ISSUE TITLE
Breaking changes after 4.3-beta.1

### ISSUE THREAD

**Issue by Creta5164** [ZachAR3/GodotOpenInEditor#5]
![image](https://github.com/ZachAR3/GodotOpenInEditor/assets/13521406/33a81b90-58f2-4971-bf87-2f9dc852930e)

I have noticed that failed to find file system dock's node.

Consider handle them by version, using `@PopupMenu@5651` for migration, `@PopupMenu@5646` for splitted files view.

**Comment by ZachAR3** [comment]
> ![image](https://private-user-images.githubusercontent.com/13521406/335845286-33a81b90-58f2-4971-bf87-2f9dc852930e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzM2NDksIm5iZiI6MTczMDczMzM0OSwicGF0aCI6Ii8xMzUyMTQwNi8zMzU4NDUyODYtMzNhODFiOTAtNThmMi00OTcxLWJmODctMmY5ZGM4NTI5MzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE1MTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNTk2ODY5MDBhZjk4ZjdiNTUzMDY1MWJmNTE0YjFlMzc0MDRlZjY5ZDQwZTIxYWU3MTA3ZjNjZmY4YjQ0NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0WQ4Mku88jqcLLZa1AZ6P_Rgz0Iemhz4Bnxrbiaenog)
> 
> I have noticed that failed to find file system dock's node.
> 
> Consider handle them by version, using `@PopupMenu@5651` for migration, `@PopupMenu@5646` for splitted files view.

Oops didn't see this until now, at this point Godot 4.4 is right around the corner so I'm going to wait to implement this nicely there as they made it so it's possible to do it in a much less janky way as you mentioned in #6
